server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://rds-mariadb.c346c7pkd3yp.ap-northeast-2.rds.amazonaws.com:3306/creation
    username: namiezexx
    password: jslee0707!
    driver-class-name: org.mariadb.jdbc.Driver
    #initialization-mode: always # classpath 에 설정한 .sql 스크립트를 기동한다.
    initialization-mode: never
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    order: 0
  social:
    kakao:
      client_id: 09fe4c6bc81e0f124df5f6d9f2d8a1e9
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me

jwt:
  header: Authorization
  secret: namiezexx@$&
  token-validity-in-seconds: 3600000

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.kyobo.dev.creation.dto

logging:
  level:
    com.kyobo.dev.creation: debug